version: '3.9'
services:
  frontend:
    image: node
    platform: linux/x86_64
    container_name: app_frontend
    working_dir: /app
    command: bash -c "npm install && npm start"
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:3000"
    restart: always
    depends_on: 
      - backend
  backend:
    image: node
    platform: linux/x86_64
    container_name: app_backend
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./backend/:/app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=EBYTR
      - DB_PORT=3306
    restart: always
    depends_on: 
      - db
  db:
    image: mysql 
    container_name: db_mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'